name: Build Flutter Multi-Platform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# نحتاج لهذه الصلاحيات ليتمكن الـ Action من الكتابة ورفع الملفات لـ GitHub Pages
permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: . 

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: update pub
        run: flutter pub upgrade --major-versions
        
      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: upgrade puh
        run: flutter pub upgrade --major-versions

      - name: Install Dependencies
        run: flutter pub get

      # قمنا بإضافة base-href لتجنب مشاكل التوجيه (Routing) في روابط GitHub
      - name: Build Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      # هذه هي الخطوة التي تقوم بالنشر الفعلي لصفحات GitHub
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web # مجلد المخرجات بعد الـ Build
